[bans]
multiple-versions = 'allow'

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "MIT", "Unicode-3.0", "MPL-2.0", "ISC", "Zlib",]
private = { ignore = true, ignore-sources = ["https://github.com/sugyan/atrium"] }
