[package]
name = "weaver-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
weaver-common = { path = "../weaver-common" }
weaver-workspace-hack = { version = "0.1", path = "../weaver-workspace-hack" }

axum = "0.7.5"
tokio = { version = "1.44", features = ["full"] }


clap = { version = "4.5", features = ["derive", "env", "cargo", "unicode"] }
