[package]
name = "weaver-common"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
n0-future = { workspace = true }
weaver-workspace-hack = { version = "0.1", path = "../weaver-workspace-hack" }
markdown-weaver = { workspace = true }
libsqlite3-sys = { version = "0.33.0", features = ["bundled"] }

atrium-api = "0.25.2"
atrium-common = "0.1.1"
atrium-identity = "0.1.3"
atrium-oauth = "0.1.1"
atrium-xrpc-client = "0.5.13"
atrium-lex = { workspace = true }

merde = { workspace = true, features = ["yaml"] }
serde = { workspace = true }
serde_json = { version = "1.0.140", features = ["preserve_order", "raw_value"] }
serde_ipld_dagcbor = { version = "0.6.1", features = ["codec"] }
serde_cbor = "0.11.2"

minijinja = { workspace = true, features = [
  "builtins",
  "debug",
  "deserialization",
  "macros",
  "multi_template",
  "adjacent_loop_items",
  "std_collections",
  "serde",
] }


miette = { workspace = true, features = ["fancy"] }
owo-colors = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

http = "1.3.1"
serde_html_form = "0.2.7"
serde_bytes = "0.11.17"
atrium-xrpc = "0.12.3"


[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[build-dependencies]
esquema-codegen = { workspace = true }
