[package]
name = "weaver-common"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
n0-future = { workspace = true }
weaver-workspace-hack = { version = "0.1", path = "../weaver-workspace-hack" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
